apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:  
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:  
      labels:
        app: "goserver"
    spec:
      serviceAccount: server
      containers:
        - name: goserver
          image: "gbofullcycle/golang-k8s:v9"

          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe: #funciona somente na inicialização
            httpGet:
              path: /healthz
              port: 8230
            periodSeconds: 4
            failureThreshold: 30



          readinessProbe:
            httpGet:
              path: /healthz
              port: 8230
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10
          
          livenessProbe: #reinicia o container
            httpGet:
              path: /healthz
              port: 8230
            periodSeconds: 5              #PERÍODO QUE SERÁ VERIFICADO (SEGUDOS)
            failureThreshold: 1           #QUANTAS VEZES TEM QUE DAR ERRO PARA REINICIAR (TOLERÂNCA DE ERROS APARA REINICIAR)
            timeoutSeconds: 1             #LIMITE DE TEMPO PARA RESPOSTA NA CONSULTA AO PATH (NESSE CASO, A URL /healthz)
            successThreshold: 1           #QUANTIDADE DE VERIFICAÇÕES POSITIVAS PARA DIZER QUE ESTÁ NO AR
            initialDelaySeconds: 15     #ESPERA UM TEMPO DETERMINADO PARA COMEÇAR

          # envFrom:
          #   - configMapRef:
          #       name: goserver-env          
     
          volumeMounts:
            - mountPath: "/myfamily"
              name: config                  
     
      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"